### ISSUE TITLE
About Generalization ability of Style Encoder

### ISSUE THREAD

**Issue by Johnson-yue** [stormraiser/adversarial-disentangle#1]
Hi， In your paper the Figures result is very good （like：Figure２，Figure６－８），but, I want to know did you test Style Encoder network with other Images which not in train data image .

**Comment by stormraiser** [comment]
I did try using a style encoder network but thus far I've only got overfitting (the style encoder would encode images in the dataset correctly but on images from a new artist the output will be near zero). I think in principle a style encoder should be possible, one just needs to find the architecture with the correct capacity.

**Comment by stormraiser** [comment]
Also, this can be done by taking the resulting style code from stage 2 as the ground truth and solve image -> style code as a regression problem, or alternatively a style encoder network can be used in place of the style code matrix in stage 2, but one might not want to substitute the style code matrix for an encoder in stage 1 for reasons that should be obvious.

**Comment by Johnson-yue** [comment]
Yes, I think so. I think your Style Encoder is overfitting in training dataset, and it can not be encode a new artist.  Do you have some idea for this?

**Comment by stormraiser** [comment]
Oh, actually you got something wrong. You should notice that in my paper S() is **NOT** an encoder, it is just a matrix that stores the learned style code of each artist, it never had the ability to map an image to its style, so by design it is impossible to generalize to new artists.

It can still generalize in the sense that although you cannot mimic the style of an image by extracting its style, you can create new styles that is (supposedly) different from the training artists by interpolating or just randomly sampling the style distribution.

What I described in the previous comments is what would happen if you replace S() with a genuine encoding network, rather than what actually happened in my paper.

**Comment by Johnson-yue** [comment]
Oh, I see , it is my fault !   you are right, in your paper S() is Not an encoder, and I want to Encode a new style of image . If I want to generate a new styles , I should finetune pretrained network in your paper. It is right way!! 

Thank you
